# Generated by Django 3.0.7 on 2020-08-11 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=50, verbose_name='Заголовок')),
                ('content', models.TextField(blank=True, default=None, max_length=1000, null=True, verbose_name='Содержание')),
                ('image', models.ImageField(upload_to='static/img/posts_images/')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
    ]
